const { withMainApplication, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// TEMPORARY DEBUG PLUGIN — writes a small native module that reads this
// APK's own signing certificate SHA-1 into the generated android/ project.
//
// android/ is gitignored and regenerated from scratch by `expo prebuild` on
// every EAS build, so hand-editing files under android/ directly does not
// survive a build — this plugin is what makes the debug module actually
// ship. Remove this file and its entry in app.config.js's `plugins` array,
// alongside the onLongPress handler in app/(auth)/login.tsx, once the
// Google Sign-In SHA-1 mismatch investigation is closed.

const moduleKt = (packageName) => `package ${packageName}

// TEMPORARY DEBUG MODULE — reads this running APK's own signing certificate
// SHA-1 to compare against what's registered in Google Cloud Console.
// Generated by plugins/withSigningCertModule.js on every prebuild; remove
// that plugin (and its app.config.js entry) once the investigation is closed.

import android.content.pm.PackageManager
import android.os.Build
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.security.MessageDigest

class SigningCertModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = "SigningCertModule"

  @ReactMethod
  fun getSigningCertSha1(promise: Promise) {
    try {
      val pm = reactApplicationContext.packageManager
      val packageName = reactApplicationContext.packageName

      val certBytes: ByteArray = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        val info = pm.getPackageInfo(packageName, PackageManager.GET_SIGNING_CERTIFICATES)
        val signingInfo = info.signingInfo
        val signers = if (signingInfo?.hasMultipleSigners() == true) {
          signingInfo.apkContentsSigners
        } else {
          signingInfo?.signingCertificateHistory
        }
        signers?.firstOrNull()?.toByteArray()
          ?: throw IllegalStateException("No signing certificate found")
      } else {
        @Suppress("DEPRECATION")
        val info = pm.getPackageInfo(packageName, PackageManager.GET_SIGNATURES)
        @Suppress("DEPRECATION")
        info.signatures?.firstOrNull()?.toByteArray()
          ?: throw IllegalStateException("No signing certificate found")
      }

      val digest = MessageDigest.getInstance("SHA1").digest(certBytes)
      val sha1 = digest.joinToString(":") { String.format("%02X", it) }
      promise.resolve(sha1)
    } catch (e: Exception) {
      promise.reject("SIGNING_CERT_ERROR", e.message, e)
    }
  }
}
`;

const packageKt = (packageName) => `package ${packageName}

// TEMPORARY DEBUG — registers SigningCertModule. Generated by
// plugins/withSigningCertModule.js on every prebuild; remove that plugin
// (and its app.config.js entry) once the investigation is closed.

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class SigningCertPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(SigningCertModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

const withSigningCertFiles = (config) =>
  withDangerousMod(config, [
    "android",
    async (config) => {
      const packageName = config.android.package;
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/java",
        ...packageName.split(".")
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "SigningCertModule.kt"), moduleKt(packageName));
      fs.writeFileSync(path.join(dir, "SigningCertPackage.kt"), packageKt(packageName));
      return config;
    },
  ]);

const withSigningCertRegistration = (config) =>
  withMainApplication(config, (config) => {
    const contents = config.modResults.contents;
    if (!contents.includes("SigningCertPackage()")) {
      config.modResults.contents = contents.replace(
        /(PackageList\(this\)\.packages\.apply\s*\{)/,
        `$1\n              // TEMPORARY DEBUG: remove alongside plugins/withSigningCertModule.js\n              add(SigningCertPackage())`
      );
    }
    return config;
  });

const withSigningCertModule = (config) =>
  withSigningCertRegistration(withSigningCertFiles(config));

module.exports = withSigningCertModule;
